### ISSUE TITLE
CMS is very slow or crashes on `interactive elements`

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#465]
Observartion:
1. Adding a snippet
2. Response takes >10s or 
3. 502 bad gateway

![Image](https://user-images.githubusercontent.com/78690362/226135820-d3cae278-a837-449e-b7ae-5e1acb6d1dd8.png)

**Comment by mattijsstam** [comment]
```

2023-03-20T07:19:46.391542611Z Internal Server Error: /wt/api/nextjs/v2/holon/
2023-03-20T07:19:46.391575012Z Traceback (most recent call last):
2023-03-20T07:19:46.391581712Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
2023-03-20T07:19:46.391587612Z     response = get_response(request)
2023-03-20T07:19:46.391598613Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
2023-03-20T07:19:46.391604713Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2023-03-20T07:19:46.391610213Z   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
2023-03-20T07:19:46.391615713Z     return view_func(*args, **kwargs)
2023-03-20T07:19:46.391620913Z   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
2023-03-20T07:19:46.391626313Z     return self.dispatch(request, *args, **kwargs)
2023-03-20T07:19:46.391631614Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
2023-03-20T07:19:46.391637014Z     response = self.handle_exception(exc)
2023-03-20T07:19:46.391642114Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
2023-03-20T07:19:46.391647514Z     self.raise_uncaught_exception(exc)
2023-03-20T07:19:46.391652814Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2023-03-20T07:19:46.391658814Z     raise exc
2023-03-20T07:19:46.391663914Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
2023-03-20T07:19:46.391669215Z     response = handler(request, *args, **kwargs)
2023-03-20T07:19:46.391674415Z   File "/home/app/web/holon/views/holon.py", line 28, in post
2023-03-20T07:19:46.391679615Z     scenario = rule_mapping.get_scenario_and_apply_rules(
2023-03-20T07:19:46.391684915Z   File "/home/app/web/holon/models/rule_mapping.py", line 32, in get_scenario_and_apply_rules
2023-03-20T07:19:46.391690215Z     rule.apply_rule_actions(filtered_queryset, value)
2023-03-20T07:19:46.391707616Z   File "/home/app/web/holon/models/scenario_rule.py", line 223, in apply_rule_actions
2023-03-20T07:19:46.391712616Z     rule_action.apply_action_to_queryset(filtered_queryset, value)
2023-03-20T07:19:46.391717216Z   File "/home/app/web/holon/models/rule_actions/rule_action_balance_group.py", line 73, in apply_action_to_queryset
2023-03-20T07:19:46.391722116Z     selected_model_type = next(
2023-03-20T07:19:46.391726416Z StopIteration
2023-03-20T07:19:48.010090684Z Unauthorized: /wt/dj-rest-auth/user/
2023-03-20T07:19:50.003104831Z Internal Server Error: /wt/api/nextjs/v2/holon/
2023-03-20T07:19:50.003141332Z Traceback (most recent call last):
2023-03-20T07:19:50.003148332Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
2023-03-20T07:19:50.003154332Z     response = get_response(request)
2023-03-20T07:19:50.003159532Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
2023-03-20T07:19:50.003171133Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2023-03-20T07:19:50.003176533Z   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
2023-03-20T07:19:50.003182033Z     return view_func(*args, **kwargs)
2023-03-20T07:19:50.003187133Z   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
2023-03-20T07:19:50.003192433Z     return self.dispatch(request, *args, **kwargs)
2023-03-20T07:19:50.003197633Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
2023-03-20T07:19:50.003202933Z     response = self.handle_exception(exc)
2023-03-20T07:19:50.003208034Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
2023-03-20T07:19:50.003213334Z     self.raise_uncaught_exception(exc)
2023-03-20T07:19:50.003218434Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2023-03-20T07:19:50.003223734Z     raise exc
2023-03-20T07:19:50.003228734Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
2023-03-20T07:19:50.003234034Z     response = handler(request, *args, **kwargs)
2023-03-20T07:19:50.003239234Z   File "/home/app/web/holon/views/holon.py", line 28, in post
2023-03-20T07:19:50.003244835Z     scenario = rule_mapping.get_scenario_and_apply_rules(
2023-03-20T07:19:50.003249835Z   File "/home/app/web/holon/models/rule_mapping.py", line 32, in get_scenario_and_apply_rules
2023-03-20T07:19:50.003255135Z     rule.apply_rule_actions(filtered_queryset, value)
2023-03-20T07:19:50.003260235Z   File "/home/app/web/holon/models/scenario_rule.py", line 223, in apply_rule_actions
2023-03-20T07:19:50.003265435Z     rule_action.apply_action_to_queryset(filtered_queryset, value)
2023-03-20T07:19:50.003286236Z   File "/home/app/web/holon/models/rule_actions/rule_action_balance_group.py", line 73, in apply_action_to_queryset
2023-03-20T07:19:50.003291336Z     selected_model_type = next(
2023-03-20T07:19:50.003295836Z StopIteration
```

**Comment by mattijsstam** [comment]
```
2023-03-20T06:46:32.866695604Z Internal Server Error: /casus-overzicht/transitievisie-warmte-gemeente/transitievisie-warmte-gemeente-uitdaging/
2023-03-20T06:46:32.866727705Z Traceback (most recent call last):
2023-03-20T06:46:32.866735005Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 929, in get_or_create
2023-03-20T06:46:32.866741205Z     return self.get(**kwargs), False
2023-03-20T06:46:32.866746905Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 650, in get
2023-03-20T06:46:32.866753205Z     raise self.model.DoesNotExist(
2023-03-20T06:46:32.866758705Z wagtail_headless_preview.models.PagePreview.DoesNotExist: PagePreview matching query does not exist.
2023-03-20T06:46:32.866764406Z
2023-03-20T06:46:32.866769606Z During handling of the above exception, another exception occurred:
2023-03-20T06:46:32.866775106Z
2023-03-20T06:46:32.866780306Z Traceback (most recent call last):
2023-03-20T06:46:32.866785706Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
2023-03-20T06:46:32.866791606Z     return self.cursor.execute(sql, params)
2023-03-20T06:46:32.866797006Z psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "wagtail_headless_preview_pagepreview_token_key"
2023-03-20T06:46:32.866802807Z DETAIL:  Key (token)=(id=65:1pe9Hs:MWSZiT4O32paU_L7-eZf6eTIBm6Jbx1SM9KCP1ounVU) already exists.
2023-03-20T06:46:32.866808207Z
2023-03-20T06:46:32.866813407Z
2023-03-20T06:46:32.866818507Z The above exception was the direct cause of the following exception:
2023-03-20T06:46:32.866823907Z
2023-03-20T06:46:32.866829007Z Traceback (most recent call last):
2023-03-20T06:46:32.866834307Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
2023-03-20T06:46:32.866839908Z     response = get_response(request)
2023-03-20T06:46:32.866845208Z   File "/usr/local/lib/python3.9/site-packages/wagtail/models/__init__.py", line 625, in _get_response
2023-03-20T06:46:32.866850708Z     response = obj.serve_preview(request, preview_mode)
2023-03-20T06:46:32.866856008Z   File "/usr/local/lib/python3.9/site-packages/wagtail_headless_preview/models.py", line 118, in serve_preview
2023-03-20T06:46:32.866861708Z     page_preview = self.create_page_preview()
2023-03-20T06:46:32.866867008Z   File "/usr/local/lib/python3.9/site-packages/wagtail_headless_preview/models.py", line 66, in create_page_preview
2023-03-20T06:46:32.866872508Z     preview, _ = PagePreview.objects.get_or_create(
2023-03-20T06:46:32.866877909Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
2023-03-20T06:46:32.866883409Z     return getattr(self.get_queryset(), name)(*args, **kwargs)
2023-03-20T06:46:32.866897409Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 936, in get_or_create
2023-03-20T06:46:32.866902709Z     return self.create(**params), True
2023-03-20T06:46:32.866908109Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 671, in create
2023-03-20T06:46:32.866913310Z     obj.save(force_insert=True, using=self.db)
2023-03-20T06:46:32.866918110Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save
2023-03-20T06:46:32.866923210Z     self.save_base(
2023-03-20T06:46:32.866928010Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 863, in save_base
2023-03-20T06:46:32.866933210Z     updated = self._save_table(
2023-03-20T06:46:32.866938010Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1006, in _save_table
2023-03-20T06:46:32.866942910Z     results = self._do_insert(
2023-03-20T06:46:32.866947810Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1047, in _do_insert
2023-03-20T06:46:32.866952711Z     return manager._insert(
2023-03-20T06:46:32.866957611Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
2023-03-20T06:46:32.866962611Z     return getattr(self.get_queryset(), name)(*args, **kwargs)
2023-03-20T06:46:32.866967511Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1791, in _insert
2023-03-20T06:46:32.866972511Z     return query.get_compiler(using=using).execute_sql(returning_fields)
2023-03-20T06:46:32.866977611Z   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
2023-03-20T06:46:32.866982611Z     cursor.execute(sql, params)
2023-03-20T06:46:32.866987411Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
2023-03-20T06:46:32.866992512Z     return self._execute_with_wrappers(
2023-03-20T06:46:32.866997312Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
2023-03-20T06:46:32.867002412Z     return executor(sql, params, many, context)
2023-03-20T06:46:32.867007112Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
2023-03-20T06:46:32.867012212Z     return self.cursor.execute(sql, params)
2023-03-20T06:46:32.867017012Z   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
2023-03-20T06:46:32.867022012Z     raise dj_exc_value.with_traceback(traceback) from exc_value
2023-03-20T06:46:32.867026812Z   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
2023-03-20T06:46:32.867031813Z     return self.cursor.execute(sql, params)
2023-03-20T06:46:32.867036613Z django.db.utils.IntegrityError: duplicate key value violates unique constraint "wagtail_headless_preview_pagepreview_token_key"
2023-03-20T06:46:32.867046413Z DETAIL:  Key (token)=(id=65:1pe9Hs:MWSZiT4O32paU_L7-eZf6eTIBm6Jbx1SM9KCP1ounVU) already exists.
2023-03-20T06:46:32.867051513Z
2023-03-20T06:46:34.027157790Z Unauthorized: /wt/dj-rest-auth/user/
2023-03-20T06:46:35.029350248Z Bad Request: /wt/api/nextjs/v2/holon/
```

**Comment by mattijsstam** [comment]
```
2023-03-20T04:09:09.946078833Z Internal Server Error: /wt/api/nextjs/v1/page_by_path/
2023-03-20T04:09:09.946122834Z Traceback (most recent call last):
2023-03-20T04:09:09.946130834Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
2023-03-20T04:09:09.946137234Z     response = get_response(request)
2023-03-20T04:09:09.946142934Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
2023-03-20T04:09:09.946149034Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2023-03-20T04:09:09.946154735Z   File "/usr/local/lib/python3.9/site-packages/wagtail/api/v2/router.py", line 68, in wrapped
2023-03-20T04:09:09.946160535Z     return func(request, *args, **kwargs)
2023-03-20T04:09:09.946166035Z   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
2023-03-20T04:09:09.946171835Z     return view_func(*args, **kwargs)
2023-03-20T04:09:09.946177535Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
2023-03-20T04:09:09.946183135Z     return self.dispatch(request, *args, **kwargs)
2023-03-20T04:09:09.946188735Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
2023-03-20T04:09:09.946194336Z     response = self.handle_exception(exc)
2023-03-20T04:09:09.946200036Z   File "/usr/local/lib/python3.9/site-packages/wagtail/api/v2/views.py", line 132, in handle_exception
2023-03-20T04:09:09.946210936Z     return super().handle_exception(exc)
2023-03-20T04:09:09.946216736Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
2023-03-20T04:09:09.946222536Z     self.raise_uncaught_exception(exc)
2023-03-20T04:09:09.946227936Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2023-03-20T04:09:09.946233737Z     raise exc
2023-03-20T04:09:09.946239137Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
2023-03-20T04:09:09.946246737Z     response = handler(request, *args, **kwargs)
2023-03-20T04:09:09.946252237Z   File "/home/app/web/nextjs/api.py", line 189, in listing_view
2023-03-20T04:09:09.946258037Z     return page.serve(request, *args, **kwargs)
2023-03-20T04:09:09.946263437Z   File "/home/app/web/main/pages/base.py", line 32, in serve
2023-03-20T04:09:09.946269138Z     json = self.get_component_data({"request": request})
2023-03-20T04:09:09.946274738Z   File "/home/app/web/main/pages/base.py", line 44, in get_component_data
2023-03-20T04:09:09.946280638Z     "component_props": self.to_dict(context, serializer_cls=serializer_cls),
2023-03-20T04:09:09.946286038Z   File "/home/app/web/main/pages/base.py", line 64, in to_dict
2023-03-20T04:09:09.947075359Z     return serializer.data
2023-03-20T04:09:09.947086559Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
2023-03-20T04:09:09.947091859Z     ret = super().data
2023-03-20T04:09:09.947096559Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
2023-03-20T04:09:09.947101559Z     self._data = self.to_representation(self.instance)
2023-03-20T04:09:09.947106260Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
2023-03-20T04:09:09.947111260Z     ret[field.field_name] = field.to_representation(attribute)
2023-03-20T04:09:09.947116060Z   File "/usr/local/lib/python3.9/site-packages/wagtail/api/v2/serializers.py", line 265, in to_representation
2023-03-20T04:09:09.947127560Z     return value.stream_block.get_api_representation(value, self.context)
2023-03-20T04:09:09.947132560Z   File "/usr/local/lib/python3.9/site-packages/wagtail/blocks/stream_block.py", line 306, in get_api_representation
2023-03-20T04:09:09.947137560Z     return [
2023-03-20T04:09:09.947142260Z   File "/usr/local/lib/python3.9/site-packages/wagtail/blocks/stream_block.py", line 309, in <listcomp>
2023-03-20T04:09:09.947147661Z     "value": child.block.get_api_representation(
2023-03-20T04:09:09.947152561Z   File "/usr/local/lib/python3.9/site-packages/wagtail/blocks/struct_block.py", line 225, in get_api_representation
2023-03-20T04:09:09.947157461Z     return {
2023-03-20T04:09:09.947162061Z   File "/usr/local/lib/python3.9/site-packages/wagtail/blocks/struct_block.py", line 226, in <dictcomp>
2023-03-20T04:09:09.947167061Z     name: self.child_blocks[name].get_api_representation(val, context=context)
2023-03-20T04:09:09.947171861Z   File "/usr/local/lib/python3.9/site-packages/wagtail/blocks/stream_block.py", line 306, in get_api_representation
2023-03-20T04:09:09.947176761Z     return [
2023-03-20T04:09:09.947181361Z   File "/usr/local/lib/python3.9/site-packages/wagtail/blocks/stream_block.py", line 309, in <listcomp>
2023-03-20T04:09:09.947186262Z     "value": child.block.get_api_representation(
2023-03-20T04:09:09.947191062Z   File "/home/app/web/main/blocks/storyline_section.py", line 62, in get_api_representation
2023-03-20T04:09:09.947195962Z     interactive_input = InteractiveElement.objects.get(pk=value["interactive_input"].id)
2023-03-20T04:09:09.947201162Z AttributeError: 'NoneType' object has no attribute 'id'
2023-03-20T06:13:07.628049604Z Internal Server Error: /wt/api/nextjs/v1/page_by_path/
2023-03-20T06:13:07.628082105Z Traceback (most recent call last):
2023-03-20T06:13:07.628088505Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
2023-03-20T06:13:07.628094005Z     response = get_response(request)
2023-03-20T06:13:07.628374812Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
2023-03-20T06:13:07.628384113Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2023-03-20T06:13:07.628389313Z   File "/usr/local/lib/python3.9/site-packages/wagtail/api/v2/router.py", line 68, in wrapped
2023-03-20T06:13:07.628394413Z     return func(request, *args, **kwargs)
2023-03-20T06:13:07.628399013Z   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
2023-03-20T06:13:07.628410113Z     return view_func(*args, **kwargs)
2023-03-20T06:13:07.628415013Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
2023-03-20T06:13:07.628420414Z     return self.dispatch(request, *args, **kwargs)
2023-03-20T06:13:07.628425014Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
2023-03-20T06:13:07.628429914Z     response = self.handle_exception(exc)
2023-03-20T06:13:07.628434714Z   File "/usr/local/lib/python3.9/site-packages/wagtail/api/v2/views.py", line 132, in handle_exception
2023-03-20T06:13:07.628439514Z     return super().handle_exception(exc)
2023-03-20T06:13:07.628444114Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
2023-03-20T06:13:07.628449114Z     self.raise_uncaught_exception(exc)
2023-03-20T06:13:07.628453614Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2023-03-20T06:13:07.628458515Z     raise exc
2023-03-20T06:13:07.628463015Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
2023-03-20T06:13:07.628467915Z     response = handler(request, *args, **kwargs)
2023-03-20T06:13:07.628472515Z   File "/home/app/web/nextjs/api.py", line 189, in listing_view
2023-03-20T06:13:07.628477215Z     return page.serve(request, *args, **kwargs)
2023-03-20T06:13:07.628481715Z   File "/home/app/web/main/pages/base.py", line 32, in serve
2023-03-20T06:13:07.628486415Z     json = self.get_component_data({"request": request})
2023-03-20T06:13:07.628491115Z   File "/home/app/web/main/pages/base.py", line 44, in get_component_data
2023-03-20T06:13:07.628495916Z     "component_props": self.to_dict(context, serializer_cls=serializer_cls),
2023-03-20T06:13:07.628500716Z   File "/home/app/web/main/pages/base.py", line 64, in to_dict
2023-03-20T06:13:07.628505316Z     return serializer.data
2023-03-20T06:13:07.628511616Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
2023-03-20T06:13:07.628516616Z     ret = super().data
2023-03-20T06:13:07.628521016Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
2023-03-20T06:13:07.628525816Z     self._data = self.to_representation(self.instance)
2023-03-20T06:13:07.628535917Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
2023-03-20T06:13:07.628540817Z     ret[field.field_name] = field.to_representation(attribute)
2023-03-20T06:13:07.628545317Z   File "/usr/local/lib/python3.9/site-packages/wagtail/api/v2/serializers.py", line 265, in to_representation
2023-03-20T06:13:07.628550117Z     return value.stream_block.get_api_representation(value, self.context)
2023-03-20T06:13:07.628554717Z   File "/usr/local/lib/python3.9/site-packages/wagtail/blocks/stream_block.py", line 306, in get_api_representation
2023-03-20T06:13:07.628559717Z     return [
2023-03-20T06:13:07.628564117Z   File "/usr/local/lib/python3.9/site-packages/wagtail/blocks/stream_block.py", line 309, in <listcomp>
2023-03-20T06:13:07.628569217Z     "value": child.block.get_api_representation(
2023-03-20T06:13:07.628573918Z   File "/usr/local/lib/python3.9/site-packages/wagtail/blocks/struct_block.py", line 225, in get_api_representation
2023-03-20T06:13:07.628578618Z     return {
2023-03-20T06:13:07.628583018Z   File "/usr/local/lib/python3.9/site-packages/wagtail/blocks/struct_block.py", line 226, in <dictcomp>
2023-03-20T06:13:07.628588018Z     name: self.child_blocks[name].get_api_representation(val, context=context)
2023-03-20T06:13:07.628592618Z   File "/usr/local/lib/python3.9/site-packages/wagtail/blocks/stream_block.py", line 306, in get_api_representation
2023-03-20T06:13:07.628597318Z     return [
2023-03-20T06:13:07.628601618Z   File "/usr/local/lib/python3.9/site-packages/wagtail/blocks/stream_block.py", line 309, in <listcomp>
2023-03-20T06:13:07.628606618Z     "value": child.block.get_api_representation(
2023-03-20T06:13:07.628611219Z   File "/home/app/web/main/blocks/storyline_section.py", line 62, in get_api_representation
2023-03-20T06:13:07.628615919Z     interactive_input = InteractiveElement.objects.get(pk=value["interactive_input"].id)
2023-03-20T06:13:07.628620619Z AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by mattijsstam** [comment]
````
2023-03-20T07:27:13.110654763Z 2023/03/20 07:27:13 [error] 33#33: *15654 upstream prematurely closed connection while reading response header from upstream, client: 172.16.170.1, server: holontool.nl, request: "GET /wt/cms/snippets/holon/interactiveelement/add/ HTTP/1.1", upstream: "http://172.16.170.2:8000/wt/cms/snippets/holon/interactiveelement/add/", host: "holon-v2-acceptatie.azurewebsites.net", referrer: "https://holon-v2-acceptatie.azurewebsites.net/wt/cms/snippets/holon/interactiveelement/"
```

**Comment by mattijsstam** [comment]
Issue is resolved by scaling up and out and increasing timeouts of nginx and gunicorn. Since the last update no 500 errors were seen despite of significant CMS traffic
