### ISSUE TITLE
Op acceptatie website werken de KPIs niet, 'bad request' nog voordat anylogic aangeroepen wordt

### ISSUE THREAD

**Issue by GillisHommen** [ZEnMo/Holon-webapp#580]
**Describe the bug**
Op acceptatie website werken de KPIs niet, 'bad request' nog voordat anylogic aangeroepen wordt geloof ik.

**To Reproduce**
1. Go to https://holon-v2-acceptatie.azurewebsites.net/casus-overzicht/bedrijventerrein-energy-hub/bedrijventerrein-energy-hub-uitdaging/
2. Move a slider, KPI dashboard turns grey briefly, then returns to blue without results

**Expected behavior**
Website should produce KPIs

**Actual behavior**
Model-run fails. When using F12 (inspect) it looks like this:
![image](https://user-images.githubusercontent.com/98752265/229808214-ff1a6ddb-13b3-46fa-893e-24cecd06a6e2.png)

**Additional context**
I suspect this may be the result of one of the interactive elements failing, as it has worked previously.

**Comment by TAVMWB** [comment]
@GillisHommen komt deze bug alleen maar voor bij deze pagina? Of ook bij de andere storylines?

**Comment by GillisHommen** [comment]
Bij de andere twee casussen kun je de pagina's van verhaallijn/challenge uberhaubt niet openen. (500
Internal Server Error.)

Bij de verhaal-modus van de energyhub krijg je hetzelfde gedrag als in dit issue beschreven.

**Comment by SCHS13** [comment]
Stacktrace:
`Traceback (most recent call last):
2023-04-05T08:37:02.872777788Z   File "/home/app/web/holon/views/holon.py", line 33, in post
2023-04-05T08:37:02.872802088Z     scenario = rule_mapping.get_scenario_and_apply_rules(
2023-04-05T08:37:02.872806988Z   File "/home/app/web/holon/models/rule_mapping.py", line 13, in get_scenario_and_apply_rules
2023-04-05T08:37:02.872810988Z     scenario = Scenario.objects.get(id=scenario_id).clone()
2023-04-05T08:37:02.872814888Z   File "/home/app/web/holon/models/scenario.py", line 105, in clone
2023-04-05T08:37:02.872818787Z     "contractScope": actor_id_to_new_model_mapping[contr.contractScope.id],
2023-04-05T08:37:02.872822887Z KeyError: 321002`

**Comment by GillisHommen** [comment]
Kan dit iets te maken hebben met het andere issue (#581 ), die nu onvolledig is ingevuld, en waarbij er manipulaties aan de contracten gedaan worden?

**Comment by TAVMWB** [comment]
Stacktrace suggereert inderdaad dat dit kwam door een verkeerde relatie. Ben benieuwd of dezelfde error zich nog voordoet op de pizzaoven, met een schone database. Zo niet, dan kunnen we deze bug sluiten i.m.o.

**Comment by thesethtruth** [comment]
@GillisHommen komt dit nog voor? Anders sluiten?
