### ISSUE TITLE
`ETMConnectionError` in `etm-service` leads to gunicorn worker timeout

### ISSUE THREAD

**Issue by thesethtruth** [Zenmo/Holon-webapp#633]
**Describe the bug**
`ETMConnectionError` leads to an incorrect termination that yields a 502 due to the gunicorn worker process shutting down

**To Reproduce**
1. Use case TVW with an incorrect scenario ID for ETM
2. Connect to the docker logs
3. Note that the Gunicorn worker process terminates

**Expected behavior**
An error at the ETM module should lead to a regular termination. 

**Additional context**
```sh
webapp-python-1  | [holon-endpoint]: Running ETM module
webapp-python-1  | [2023-04-19 13:44:52 +0200] [755] [INFO] Worker exiting (pid: 755)
webapp-python-1  | Traceback (most recent call last):
webapp-python-1  |   File "/usr/local/bin/gunicorn", line 8, in <module>
webapp-python-1  |     sys.exit(run())
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
webapp-python-1  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 231, in run
webapp-python-1  |     super().run()
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
webapp-python-1  |     Arbiter(self).run()
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 211, in run
webapp-python-1  |     self.manage_workers()
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
webapp-python-1  |     self.spawn_workers()
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 622, in spawn_workers
webapp-python-1  |     self.spawn_worker()
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
webapp-python-1  |     worker.init_process()
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 142, in init_process
webapp-python-1  |     self.run()
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 125, in run
webapp-python-1  |     self.run_for_one(timeout)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 69, in run_for_one
webapp-python-1  |     self.accept(listener)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 31, in accept
webapp-python-1  |     self.handle(listener, client, addr)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 136, in handle
webapp-python-1  |     self.handle_request(listener, req, client, addr)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
webapp-python-1  |     respiter = self.wsgi(environ, resp.start_response)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 131, in __call__
webapp-python-1  |     response = self.get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 140, in get_response
webapp-python-1  |     response = self._middleware_chain(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
webapp-python-1  |     response = get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
webapp-python-1  |     response = response or self.get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
webapp-python-1  |     response = get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
webapp-python-1  |     response = response or self.get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
webapp-python-1  |     response = get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
webapp-python-1  |     response = response or self.get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
webapp-python-1  |     response = get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
webapp-python-1  |     response = response or self.get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
webapp-python-1  |     response = get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
webapp-python-1  |     response = response or self.get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
webapp-python-1  |     response = get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
webapp-python-1  |     response = response or self.get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
webapp-python-1  |     response = get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
webapp-python-1  |     response = response or self.get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
webapp-python-1  |     response = get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
webapp-python-1  |     response = response or self.get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
webapp-python-1  |     response = get_response(request)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
webapp-python-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
webapp-python-1  |     return view_func(*args, **kwargs)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
webapp-python-1  |     return self.dispatch(request, *args, **kwargs)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
webapp-python-1  |     response = handler(request, *args, **kwargs)
webapp-python-1  |   File "/home/app/web/holon/views/holon.py", line 57, in post
webapp-python-1  |     for name, outcome in ETMConnect.connect_from_scenario(
webapp-python-1  |   File "/home/app/web/holon/services/query_and_convert.py", line 55, in connect_from_scenario
webapp-python-1  |     yield ETMConnect.upscaling(config)
webapp-python-1  |   File "/home/app/web/holon/services/query_and_convert.py", line 70, in upscaling
webapp-python-1  |     new_scenario_id = etm_service.scale_copy_and_send(
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/etm_service/__init__.py", line 105, in scale_copy_and_send
webapp-python-1  |     return scale_copy_and_send_from_requests(scenario_id, holon_outcomes, data_requests)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/etm_service/__init__.py", line 148, in scale_copy_and_send_from_requests
webapp-python-1  |     scenario_copy = next(ETMConnection('copy', scenario_id).connect(None))
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/etm_service/etm_session/__init__.py", line 55, in connect
webapp-python-1  |     yield from self.session.send_request(requested_keys)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/etm_service/etm_session/copy.py", line 12, in send_request
webapp-python-1  |     yield self._handle_response(requests.post(Config().api_url, json=payload))
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/etm_service/etm_session/copy.py", line 18, in _handle_response
webapp-python-1  |     return super()._handle_response(response)
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/etm_service/etm_session/session.py", line 32, in _handle_response
webapp-python-1  |     self.fail_with(errors=response.json()['errors'])
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/etm_service/etm_session/session.py", line 39, in fail_with
webapp-python-1  |     raise ETMConnectionError(message)
webapp-python-1  | etm_service.etm_session.session.ETMConnectionError: scenario_id
webapp-python-1  | [2023-04-19 11:44:54 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:755)
webapp-python-1  | Exception ignored in: <module 'threading' from '/usr/local/lib/python3.9/threading.py'>
webapp-python-1  | Traceback (most recent call last):
webapp-python-1  |   File "/usr/local/lib/python3.9/threading.py", line 1477, in _shutdown
webapp-python-1  |     lock.acquire()
webapp-python-1  |   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
webapp-python-1  |     sys.exit(1)
webapp-python-1  | SystemExit: 1
webapp-python-1  | [2023-04-19 11:44:55 +0000] [1] [WARNING] Worker with pid 755 was terminated due to signal 9
```

**Comment by thesethtruth** [comment]
closed by https://github.com/ZEnMo/Holon-webapp/pull/648

**Comment by Erikvv** [comment]
Vandaag ondervonden dat dit nog steeds speelt en probleemoplossing in de weg zit omdat de Sentry tracing niet compleet is.

```
2023-06-23T09:31:23.386769797Z [holon-endpoint] [23-06-2023 11:31:23]: Applying interactive elements to scenario
2023-06-23T09:31:25.531736520Z [holon-endpoint] [23-06-2023 11:31:25]: Running Anylogic model
2023-06-23T09:31:25.846549902Z [holon-endpoint] [23-06-2023 11:31:25]: Running ETM module
2023-06-23T09:31:30.348457938Z 2023/06/23 09:31:30 [error] 35#35: *5154 upstream prematurely closed connection while reading response header from upstream, client: 172.19.177.1, server: ${server_name}, request: "POST /wt/api/nextjs/v2/holon/ HTTP/1.1", upstream: "http://172.19.177.2:8000/wt/api/nextjs/v2/holon/", host: "holon-v2-acceptatie.azurewebsites.net", referrer: "https://holon-v2-acceptatie.azurewebsites.net/casus-overzicht/buurtelektrificatie/uitdaging-buurtelectrificatie/"
2023-06-23T09:31:30.353991491Z [2023-06-23 11:31:30 +0200] [270] [INFO] Worker exiting (pid: 270)
2023-06-23T09:31:30.365252797Z Traceback (most recent call last):
2023-06-23T09:31:30.365300098Z   File "/usr/local/bin/gunicorn", line 8, in <module>
2023-06-23T09:31:30.365398099Z     sys.exit(run())
2023-06-23T09:31:30.365419899Z   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
2023-06-23T09:31:30.365425999Z     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2023-06-23T09:31:30.365430699Z   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 231, in run
2023-06-23T09:31:30.366494609Z     super().run()
2023-06-23T09:31:30.366514809Z   File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
2023-06-23T09:31:30.366520509Z     Arbiter(self).run()
2023-06-23T09:31:30.366524709Z   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 202, in run
2023-06-23T09:31:30.366529309Z     self.manage_workers()
2023-06-23T09:31:30.366533709Z   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
2023-06-23T09:31:30.367171516Z     self.spawn_workers()
2023-06-23T09:31:30.367694720Z   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 622, in spawn_workers
2023-06-23T09:31:30.369233835Z     self.spawn_worker()
2023-06-23T09:31:30.369251235Z   File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2023-06-23T09:31:30.369257635Z     worker.init_process()
2023-06-23T09:31:30.369278235Z   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 142, in init_process
2023-06-23T09:31:30.369284236Z     self.run()
2023-06-23T09:31:30.369289336Z   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 125, in run
2023-06-23T09:31:30.369389637Z     self.run_for_one(timeout)
2023-06-23T09:31:30.370371946Z   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 69, in run_for_one
2023-06-23T09:31:30.370975852Z     self.accept(listener)
2023-06-23T09:31:30.370995752Z   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 31, in accept
2023-06-23T09:31:30.371650958Z     self.handle(listener, client, addr)
2023-06-23T09:31:30.371688358Z   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 136, in handle
2023-06-23T09:31:30.372245264Z     self.handle_request(listener, req, client, addr)
2023-06-23T09:31:30.372265164Z   File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
2023-06-23T09:31:30.372902970Z     respiter = self.wsgi(environ, resp.start_response)
2023-06-23T09:31:30.372921470Z   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/__init__.py", line 137, in sentry_patched_wsgi_handler
2023-06-23T09:31:30.373615177Z     return SentryWsgiMiddleware(bound_old_app, use_x_forwarded_for)(
2023-06-23T09:31:30.373636277Z   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/wsgi.py", line 115, in __call__
2023-06-23T09:31:30.373643177Z     reraise(*_capture_exception(hub))
2023-06-23T09:31:30.373657377Z   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 60, in reraise
2023-06-23T09:31:30.374899289Z     raise value
2023-06-23T09:31:30.374921289Z   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/wsgi.py", line 108, in __call__
2023-06-23T09:31:30.374928589Z     rv = self.app(
2023-06-23T09:31:30.374933689Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 131, in __call__
2023-06-23T09:31:30.375968899Z     response = self.get_response(request)
2023-06-23T09:31:30.375988799Z   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/__init__.py", line 417, in sentry_patched_get_response
2023-06-23T09:31:30.375995699Z     rv = old_get_response(self, request)
2023-06-23T09:31:30.376000799Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 140, in get_response
2023-06-23T09:31:30.377584314Z     response = self._middleware_chain(request)
2023-06-23T09:31:30.377603214Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
2023-06-23T09:31:30.377609814Z     response = get_response(request)
2023-06-23T09:31:30.377614914Z   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/middleware.py", line 173, in __call__
2023-06-23T09:31:30.377631815Z     return f(*args, **kwargs)
2023-06-23T09:31:30.377637415Z   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
2023-06-23T09:31:30.377644715Z     response = response or self.get_response(request)
2023-06-23T09:31:30.377955718Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
2023-06-23T09:31:30.378363722Z     response = get_response(request)
2023-06-23T09:31:30.378384522Z   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/middleware.py", line 173, in __call__
2023-06-23T09:31:30.379037628Z     return f(*args, **kwargs)
2023-06-23T09:31:30.379165529Z   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
2023-06-23T09:31:30.379665434Z     response = response or self.get_response(request)
2023-06-23T09:31:30.379899336Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
2023-06-23T09:31:30.380318740Z     response = get_response(request)
2023-06-23T09:31:30.380447041Z   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/middleware.py", line 173, in __call__
2023-06-23T09:31:30.381000446Z     return f(*args, **kwargs)
2023-06-23T09:31:30.381645153Z   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
2023-06-23T09:31:30.382057156Z     response = response or self.get_response(request)
2023-06-23T09:31:30.386816002Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
2023-06-23T09:31:30.386840702Z     response = get_response(request)
2023-06-23T09:31:30.386848502Z   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/middleware.py", line 173, in __call__
2023-06-23T09:31:30.386854302Z     return f(*args, **kwargs)
2023-06-23T09:31:30.386859802Z   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
2023-06-23T09:31:30.386958103Z     response = response or self.get_response(request)
2023-06-23T09:31:30.387254306Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
2023-06-23T09:31:30.387262106Z     response = get_response(request)
2023-06-23T09:31:30.387283806Z   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/middleware.py", line 173, in __call__
2023-06-23T09:31:30.387299206Z     return f(*args, **kwargs)
2023-06-23T09:31:30.387304406Z   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
2023-06-23T09:31:30.389927231Z     response = response or self.get_response(request)
2023-06-23T09:31:30.389937531Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
2023-06-23T09:31:30.389954031Z     response = get_response(request)
2023-06-23T09:31:30.389958931Z   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/middleware.py", line 173, in __call__
2023-06-23T09:31:30.389963431Z     return f(*args, **kwargs)
2023-06-23T09:31:30.389967631Z   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
2023-06-23T09:31:30.389972031Z     response = response or self.get_response(request)
2023-06-23T09:31:30.389976231Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
2023-06-23T09:31:30.389980731Z     response = get_response(request)
2023-06-23T09:31:30.389984732Z   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/middleware.py", line 173, in __call__
2023-06-23T09:31:30.389989032Z     return f(*args, **kwargs)
2023-06-23T09:31:30.389993132Z   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
2023-06-23T09:31:30.389997532Z     response = response or self.get_response(request)
2023-06-23T09:31:30.390001632Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
2023-06-23T09:31:30.390006032Z     response = get_response(request)
2023-06-23T09:31:30.390010132Z   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/middleware.py", line 173, in __call__
2023-06-23T09:31:30.390014532Z     return f(*args, **kwargs)
2023-06-23T09:31:30.390020532Z   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
2023-06-23T09:31:30.390025432Z     response = response or self.get_response(request)
2023-06-23T09:31:30.390029532Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
2023-06-23T09:31:30.390033832Z     response = get_response(request)
2023-06-23T09:31:30.390037932Z   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
2023-06-23T09:31:30.390042332Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2023-06-23T09:31:30.390046532Z   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
2023-06-23T09:31:30.390050832Z     return view_func(*args, **kwargs)
2023-06-23T09:31:30.390054932Z   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
2023-06-23T09:31:30.390059332Z     return self.dispatch(request, *args, **kwargs)
2023-06-23T09:31:30.390063432Z   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
2023-06-23T09:31:30.390067632Z     response = handler(request, *args, **kwargs)
2023-06-23T09:31:30.390071932Z   File "/home/app/web/holon/views/holon.py", line 91, in post
2023-06-23T09:31:30.390076132Z     etm_outcomes = self._etm_results(scenario, scenario_aggregate, cc)
2023-06-23T09:31:30.390083732Z   File "/home/app/web/holon/views/holon.py", line 147, in _etm_results
2023-06-23T09:31:30.390088133Z     for module, outcome in ETMConnect.connect_from_scenario(
2023-06-23T09:31:30.390092333Z   File "/home/app/web/holon/services/query_and_convert.py", line 82, in connect_from_scenario
2023-06-23T09:31:30.390096533Z     yield ETMConnect.upscaling(config)
2023-06-23T09:31:30.390100733Z   File "/home/app/web/pipit/sentry.py", line 144, in inner
2023-06-23T09:31:30.390105033Z     return sentry_sdk.trace(func)(*args, **kwargs)
2023-06-23T09:31:30.390109033Z   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/tracing_utils_py3.py", line 70, in func_with_tracing
2023-06-23T09:31:30.390126233Z     return func(*args, **kwargs)
2023-06-23T09:31:30.390132033Z   File "/home/app/web/holon/services/query_and_convert.py", line 127, in upscaling
2023-06-23T09:31:30.390136433Z     new_scenario_id = etm_service.scale_copy_and_send(config.etm_scenario_id, config.queries)
2023-06-23T09:31:30.390140633Z   File "/usr/local/lib/python3.9/site-packages/etm_service/__init__.py", line 105, in scale_copy_and_send
2023-06-23T09:31:30.390145033Z     return scale_copy_and_send_from_requests(scenario_id, data_requests)
2023-06-23T09:31:30.390149233Z   File "/usr/local/lib/python3.9/site-packages/etm_service/__init__.py", line 136, in scale_copy_and_send_from_requests
2023-06-23T09:31:30.390153633Z     data_requests.combine(RequestsToOne())
2023-06-23T09:31:30.390157733Z   File "/usr/local/lib/python3.9/site-packages/etm_service/data_requests.py", line 23, in combine
2023-06-23T09:31:30.390162233Z     combiner.inject(single_request)
2023-06-23T09:31:30.390166433Z   File "/usr/local/lib/python3.9/site-packages/etm_service/combiner.py", line 38, in inject
2023-06-23T09:31:30.390202034Z     raise MissingRequestInfoException(
2023-06-23T09:31:30.390207834Z etm_service.single_request.converter.MissingRequestInfoException: Setting households_heater_heatpump_air_water_electricity_share_internal: on SET action conversions can't be blank
```

**Comment by Erikvv** [comment]
Had ik volgens mij gefixt. Probleem zat in de verkeerde base class voor de Exception waardoor deze niet gecatched werd.
