### ISSUE TITLE
`costbenefit` crashes on some cases

### ISSUE THREAD

**Issue by thesethtruth** [ZEnMo/Holon-webapp#640]
**Describe the bug**

**To Reproduce**
1. Checkout to main
2. Run pizzaoven in the cloud
3. Send a request to the `/holon` endpoint and notice that some cases do not succeed.

**Expected behavior**
This error shouldn't occur, calculations should be carried out like normal. 

**Actual behavior**
```sh
webapp-python-1 | [holon-endpoint]: Running ETM module
webapp-python-1 | [holon-endpoint]: Running CostBenedict module
webapp-python-1 | [holon-endpoint]: Traceback (most recent call last):
webapp-python-1 | File "/home/app/web/holon/views/holon.py", line 69, in post
webapp-python-1 | cost_benefit_results = CostBenedict( 
webapp-python-1 | File "/home/app/web/holon/services/costbenefit.py", line 35, in determine_group_costs
webapp-python-1 | return self.determine_cost(groupby="group", want_to_know=self.want_to_know) 
webapp-python-1 | File "/home/app/web/holon/services/costbenefit.py", line 83, in determine_cost
webapp-python-1 | return dict(sorted(direct_transactions.items())) 
webapp-python-1 | TypeError: '<' not supported between instances of 'NoneType' and 'str'

```

**Comment by thesethtruth** [comment]
Casus TVW (`456001`) succeeded on `main` without interactive elements. See log below. 


```sh
webapp-python-1  | [holon-endpoint]: Cloning scenario 456001
webapp-python-1  | [holon-endpoint]: Running Anylogic model
webapp-python-1  | Not Found: /wt/api/nextjs/dj-rest-auth/user/
webapp-python-1  | [holon-endpoint]: Running ETM module
webapp-python-1  | [QConfig]: Couldn't find the specified key 'shareElectricvehiclesInHouseholds' in any of the AnyLogic results (resort to convert with 1)
webapp-python-1  | [QConfig]: Couldn't find the specified key 'shareElectricvehiclesInHouseholds' in any of the AnyLogic results (resort to convert with 1)
webapp-python-1  | [holon-endpoint]: Running CostBenedict module
webapp-python-1  | groups
webapp-python-1  | HOLON (energie)
webapp-python-1  | COMMERCIAL
webapp-python-1  | HOUSEHOLD
webapp-python-1  | --------- inverse_transactions ---------
webapp-python-1  | {
webapp-python-1  |   "Energieleverancier": {
webapp-python-1  |     "HOLON (energie)": 0.0,
webapp-python-1  |     "COMMERCIAL": 174986.9,
webapp-python-1  |     "HOUSEHOLD": 604851.04
webapp-python-1  |   },
webapp-python-1  |   "Netbeheerder": {
webapp-python-1  |     "HOLON (energie)": 0.0,
webapp-python-1  |     "COMMERCIAL": 0.0,
webapp-python-1  |     "HOUSEHOLD": 0.0
webapp-python-1  |   },
webapp-python-1  |   "Overheid": {
webapp-python-1  |     "HOLON (energie)": 0.0,
webapp-python-1  |     "COMMERCIAL": 126931.44000000002,
webapp-python-1  |     "HOUSEHOLD": 478308.8199999996
webapp-python-1  |   },
webapp-python-1  |   "HOLON (energie)": {
webapp-python-1  |     "HOLON (energie)": 0,
webapp-python-1  |     "COMMERCIAL": 0,
webapp-python-1  |     "HOUSEHOLD": 0
webapp-python-1  |   }
webapp-python-1  | }
webapp-python-1  | --------- direct transations ---------
webapp-python-1  | {
webapp-python-1  |   "HOLON (energie)": {
webapp-python-1  |     "Energieleverancier": 0,
webapp-python-1  |     "Netbeheerder": 0,
webapp-python-1  |     "Overheid": 0,
webapp-python-1  |     "HOLON (energie)": 0,
webapp-python-1  |     "COMMERCIAL": 0,
webapp-python-1  |     "HOUSEHOLD": 0
webapp-python-1  |   },
webapp-python-1  |   "COMMERCIAL": {
webapp-python-1  |     "Energieleverancier": -174987,
webapp-python-1  |     "Netbeheerder": 0,
webapp-python-1  |     "Overheid": -126931,
webapp-python-1  |     "HOLON (energie)": 0
webapp-python-1  |   },
webapp-python-1  |   "HOUSEHOLD": {
webapp-python-1  |     "Energieleverancier": -604851,
webapp-python-1  |     "Netbeheerder": 0,
webapp-python-1  |     "Overheid": -478309,
webapp-python-1  |     "HOLON (energie)": 0
webapp-python-1  |   },
webapp-python-1  |   "Energieleverancier": {
webapp-python-1  |     "HOLON (energie)": 0,
webapp-python-1  |     "COMMERCIAL": 174987,
webapp-python-1  |     "HOUSEHOLD": 604851
webapp-python-1  |   },
webapp-python-1  |   "Netbeheerder": {
webapp-python-1  |     "HOLON (energie)": 0,
webapp-python-1  |     "COMMERCIAL": 0,
webapp-python-1  |     "HOUSEHOLD": 0
webapp-python-1  |   },
webapp-python-1  |   "Overheid": {
webapp-python-1  |     "HOLON (energie)": 0,
webapp-python-1  |     "COMMERCIAL": 126931,
webapp-python-1  |     "HOUSEHOLD": 478309
webapp-python-1  |   }
webapp-python-1  | }
webapp-python-1  | [holon-endpoint]: 200 OK
```

**Comment by thesethtruth** [comment]
closed because kosten baten versie 2 implemented
